FROM pymssql/pymssql

RUN apt-get update && apt-get install -y \
    python3-pip

WORKDIR /app

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY . /app/

CMD [ "python3", "scom_bot.py"]